version: "3.8"

name: corewebhook
services:
    postgres:
        image: postgres:latest
        container_name: corewebhook_db
        ports:
            - "127.0.0.1:55432:5432"
        environment:
            POSTGRES_USER: corewebhook
            POSTGRES_PASSWORD: corewebhook
            POSTGRES_DB: corewebhook
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack
        ports:
            - "127.0.0.1:4566:4566" # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559" # external services port range
        environment:
            - DEBUG=${DEBUG-}
            - DOCKER_HOST=unix:///var/run/docker.sock
            - AWS_ACCESS_KEY_ID=localstack-access-key
            - AWS_SECRET_ACCESS_KEY=localstack-secret-key
            - AWS_DEFAULT_REGION=ap-northeast-2
            # - SERVICES=sqs
        volumes:
            - "./localstack/volume:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
            # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
